
input_file = "sample.txt"
mobile_file = "mobnos_output.txt"
email_file = "emails_output.txt"
invalid_file = "invalid_output.txt"
character_file = "char_output.txt"
number_file = "number_output.txt"
special_char_file = "special_char_output.txt"
write_mode = "w"
csv_file = "empsal_part_buck.csv"